// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wiki_timeline_api.Data;

#nullable disable

namespace wiki_timeline_api.Data.Migrations
{
    [DbContext(typeof(WikiTimelineContext))]
    [Migration("20261007174856_UpdateDbSchema")]
    partial class UpdateDbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGame", b =>
                {
                    b.Property<int>("DailyGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.HasKey("DailyGameID");

                    b.HasIndex("CreationDate")
                        .IsUnique();

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGameEntity", b =>
                {
                    b.Property<int>("DailyGameEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyGameID")
                        .HasColumnType("int");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.HasKey("DailyGameEntityID");

                    b.HasIndex("DailyGameID");

                    b.HasIndex("EntityID");

                    b.ToTable("DailyGameEntities");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.Entity", b =>
                {
                    b.Property<int>("EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("LastUsedAt")
                        .HasColumnType("date");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EntityID");

                    b.HasIndex("ThemeID", "ExternalID", "DateType")
                        .IsUnique();

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.Theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ThemeID");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGame", b =>
                {
                    b.Property<int>("UserGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DailyGameID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserGameID");

                    b.HasIndex("DailyGameID");

                    b.HasIndex("UserID");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGameEntry", b =>
                {
                    b.Property<int>("UserGameEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyGameEntityID")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("UserGameID")
                        .HasColumnType("int");

                    b.HasKey("UserGameEntryID");

                    b.HasIndex("DailyGameEntityID");

                    b.HasIndex("UserGameID");

                    b.ToTable("UserGameEntries");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGameEntity", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.DailyGame", "DailyGame")
                        .WithMany("DailyGameEntities")
                        .HasForeignKey("DailyGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wiki_timeline_api.Entities.Entity", "Entity")
                        .WithMany("DailyGameEntities")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGame");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.Entity", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.Theme", "Theme")
                        .WithMany("Entities")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGame", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.DailyGame", "DailyGame")
                        .WithMany()
                        .HasForeignKey("DailyGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wiki_timeline_api.Entities.User", "User")
                        .WithMany("UserGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGameEntry", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.DailyGameEntity", "DailyGameEntity")
                        .WithMany()
                        .HasForeignKey("DailyGameEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wiki_timeline_api.Entities.UserGame", "UserGame")
                        .WithMany()
                        .HasForeignKey("UserGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGameEntity");

                    b.Navigation("UserGame");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGame", b =>
                {
                    b.Navigation("DailyGameEntities");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.Entity", b =>
                {
                    b.Navigation("DailyGameEntities");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.Theme", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
