// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wiki_timeline_api.Data;

#nullable disable

namespace wiki_timeline_api.Data.Migrations
{
    [DbContext(typeof(WikiTimelineContext))]
    partial class WikiTimelineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGame", b =>
                {
                    b.Property<int>("DailyGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.HasKey("DailyGameID");

                    b.ToTable("DailyGames");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGameCard", b =>
                {
                    b.Property<int>("DailyGameCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DailyGameID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("EventDateType")
                        .HasColumnType("int");

                    b.Property<int>("WikiID")
                        .HasColumnType("int");

                    b.Property<string>("WikiImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WikiProperty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WikiTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DailyGameCardID");

                    b.HasIndex("DailyGameID");

                    b.ToTable("DailyGameCards");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGame", b =>
                {
                    b.Property<int>("UserGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<int>("DailyGameID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserGameID");

                    b.HasIndex("DailyGameID");

                    b.HasIndex("UserID");

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGameCard", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.DailyGame", "DailyGame")
                        .WithMany("DailyGameCards")
                        .HasForeignKey("DailyGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGame");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.UserGame", b =>
                {
                    b.HasOne("wiki_timeline_api.Entities.DailyGame", "DailyGame")
                        .WithMany()
                        .HasForeignKey("DailyGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wiki_timeline_api.Entities.User", "User")
                        .WithMany("UserGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyGame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.DailyGame", b =>
                {
                    b.Navigation("DailyGameCards");
                });

            modelBuilder.Entity("wiki_timeline_api.Entities.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
